---
- name: Install Java
  become: yes
  hosts: appserver
  tasks:
    - name: install openjdk 11
      package:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "Debian"
    - name: install java on redhat
      ansible.builtin.yum:
        name: java-11-openjdk
        update_cache: yes
        state: present
      when: ansible_facts['os_family'] == "RedHat"
           
           
           

        