---
- name: Install Java
  become: yes
  hosts: all
  tasks:
    - name: install java on redhat
      ansible.builtin.yum:
        name: java-11-openjdk
        update_cache: yes
        state: present
        